{{- if .Values.ingress.enabled -}}
{{- $domainName := include "publicAddress.domainName" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elasticsearch.fullname" . }}-elasticsearch
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    ingress.kubernetes.io/secure-backends: "false"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/auth/login"
spec:
  tls:
    - secretName: {{ .Values.global.httpsCertSecret }}
      {{- if $domainName }}
      hosts:
        - {{ $domainName }}
      {{- end }}

  rules:
    - {{- if $domainName }}
      host: {{ $domainName }}
      {{ else }}
      # host:  ## Not specified because global.PublicAddress is an IP address
      {{ end -}}
      http:
        paths:
          - path: /elasticsearch/?(.*)
            backend:
              serviceName: pure1-unplugged-elasticsearch-client
              servicePort: 9200

{{ end }}
